//
//  Workspace.swift
//  TestProjectManifests
//
//  Created by Junyoung on 1/8/25.
//

@preconcurrency import ProjectDescription

let workspace = Workspace(
    name: "MVL-iOS",
    projects: [
        "Projects/**"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled,
        renderMarkdownReadme: true
    )
)

