//
//  Workspace.swift
//  CleanArchitectureSampleAppManifests
//
//  Created by saeng lin on 1/23/25.
//

@preconcurrency import ProjectDescription

let workspace = Workspace(
    name: "CleanArchitectureSampleApp",
    projects: [
        "Projects/**"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled,
        renderMarkdownReadme: true
    )
)
